import {Link} from '@/i18n/navigation';

type Locale = 'en' | 'zh-CN';
const copy = { 'zh-CN': {repo: '查看工程仓库', built: '已实现', progress: '实现中 / 真机验证中'}, en: {repo: 'View engineering repository', built: 'Implemented', progress: 'Implemented / device validation in progress'} } as const;

function Chapter({number, title, children}: {number: string; title: string; children: React.ReactNode}) { return <section className="project-section"><p className="project-number">{number}</p><h2>{title}</h2>{children}</section>; }

function CapabilityTable({locale}: {locale: Locale}) {
  const zh = locale === 'zh-CN';
  const rows = zh ? [['Calendar Create','✅','已实现','MacAgentHost + EventKit，创建后经过状态验证。'],['Calendar Query','✅','已实现','当前主要用于 Create 后的 verify_state。'],['Real EventKit Execution','✅','已实现','真实执行边界已建立；当前能力范围仍有限。'],['Verification','✅','已实现','Tool success 不能直接等于 Task success。'],['iPhone Shortcut / HTTP','✅','已实现','用户入口和 HTTP API 已实现；真实设备链路需单独验收。'],['Remote HTTPS / Siri','🟡','进行中','配置和代码路径存在，公网与真机回归不能假设为完全验证。'],['Clarification / Resume','🟡','实现中 / 真机验证中','代码已实现，真实 iPhone/Siri 多轮验证仍在进行。'],['Production LLM','⏳','Planned','当前 DemoLLM 是确定性的开发适配器。'],['Reminder / Update / Delete','⏳','Planned','协议中有合同形状，但当前不是可执行能力。'],['Mail / Files / Browser','⏳','Roadmap','未来 Personal Agent 能力。']] : [['Calendar Create','✅','Implemented','MacAgentHost + EventKit, followed by state verification.'],['Calendar Query','✅','Implemented','Currently used mainly for Create verification.'],['Real EventKit Execution','✅','Implemented','The real execution boundary exists; the capability scope is still narrow.'],['Verification','✅','Implemented','Tool success is not automatically Task success.'],['iPhone Shortcut / HTTP','✅','Implemented','The user entry point and HTTP API exist; device access needs separate acceptance.'],['Remote HTTPS / Siri','🟡','In progress','The code path exists; public and device regression is not claimed as complete.'],['Clarification / Resume','🟡','Implemented / device validation in progress','Implemented in code; real device validation is still pending.'],['Production LLM','⏳','Planned','DemoLLM is a deterministic development adapter.'],['Reminder / Update / Delete','⏳','Planned','Contracts exist, but these are not executable capabilities yet.'],['Mail / Files / Browser','⏳','Roadmap','Future Personal Agent capabilities.']];
  return <div className="capability-table">{rows.map(([name, icon, state, detail]) => <div key={name}><strong>{icon} {name}</strong><span className={`tag ${icon === '✅' ? 'tag-green' : icon === '🟡' ? 'tag-yellow' : ''}`}>{state}</span><p>{detail}</p></div>)}</div>;
}

export function CalendarAgentProject({locale}: {locale: Locale}) {
  const zh = locale === 'zh-CN';
  const flow = (text: string) => <pre className="project-flow">{text}</pre>;
  return <div className="project-page">
    <section className="project-hero"><p className="eyebrow">{zh ? 'Agent 构建 · Reference Project' : 'Agent building · Reference project'}</p><h1>Calendar Agent</h1><p className="project-deck">{zh ? '从自然语言到真实 macOS Calendar：一个 Mac-first Personal Agent 的完整工程实践。' : 'From natural language to a real macOS Calendar: an engineering record of a Mac-first Personal Agent.'}</p><p className="project-summary">{zh ? '这不是“LLM + Calendar API”的演示，而是一个从 0 开始建立 Task、State、Tool Calling、Persistence、Verification、Remote Access 和 Agent QA 的真实项目。' : 'This is not an “LLM + Calendar API” demo. It is a real project built around Task, State, Tool Calling, Persistence, Verification, Remote Access, and Agent QA.'}</p><div className="project-links"><a className="primary-button" href="https://github.com/Kristenqingran/calendar-agent" target="_blank" rel="noreferrer">{copy[locale].repo} ↗</a><a className="project-text-link" href="#overview">{zh ? '开始阅读项目故事' : 'Start the project story'} ↓</a></div></section>

    <Chapter number="00 · PROJECT OVERVIEW" title={zh ? '我到底做了什么？' : 'What did I build?'}><div id="overview" className="architecture-diagram"><div>User<br/><small>iPhone · Siri · Apple Watch</small></div><span>→</span><div>Shortcut<br/><small>HTTPS</small></div><span>→</span><div>AgentRuntime<br/><small>analysis · state · clarification · planner</small></div><span>→</span><div>Tool Execution Layer<br/><small>MacAgentHost</small></div><span>→</span><div>EventKit<br/><small>macOS Calendar</small></div><span>→</span><div>Verification<br/><small>Final response</small></div></div><p>{zh ? '用户提交自然语言会话请求，AgentRuntime 管理任务和参数，Tool Execution Layer 把受约束的操作交给 MacAgentHost，EventKit 产生真实 Calendar 状态，Verification 再决定最终响应。' : 'The user submits a natural-language session request, AgentRuntime manages task and parameter state, the Tool Execution Layer sends a constrained operation to MacAgentHost, EventKit creates real Calendar state, and Verification decides the final response.'}</p><h3 className="project-subheading">{zh ? '当前能力状态' : 'Current capability status'}</h3><CapabilityTable locale={locale}/></Chapter>

    <Chapter number="01 · FROM IDEA TO PROTOTYPE" title={zh ? '从 Idea 到第一个 Agent Prototype' : 'From idea to the first Agent Prototype'}><p>{zh ? '最初的问题是：如果我对 Siri 说一句自然语言，能不能让自己的 Agent 真正理解并操作 Calendar？最早的抽象只有三层：Natural Language → Agent → Calendar Action。' : 'The first question was: if I speak a natural-language request to Siri, can my own agent understand it and operate Calendar? The first abstraction had three layers: Natural Language → Agent → Calendar Action.'}</p>{flow(`UserRequest\n    ↓\nAgentRuntime\n    ↓\nLLM / Semantic Analysis\n    ↓\nPlanner\n    ↓\nMock Tool\n    ↓\nFinal`)}<p>{zh ? '先使用 Mock Tool，是为了验证 Agent Core、Task、Parameter、Planner 和 Tool Contract，而不是一开始就同时处理 macOS 权限、EventKit、网络和 Siri。' : 'The Mock Tool came first so the Agent Core, Task, Parameter, Planner, and Tool Contract could be validated before adding macOS permissions, EventKit, networking, and Siri.'}</p></Chapter>

    <Chapter number="02 · BUILDING THE AGENT CORE" title={zh ? 'Agent 到底比普通 API 多了什么？' : 'What makes an agent more than an API?'}><p>{zh ? '“明天下午三点开一个小时会议”不能直接变成 API 参数，而要经过语义分析、任务状态和规划。参数拥有 value、source、status；任务拥有 conversation、task、step 等关联。' : '“Create a one-hour meeting tomorrow at 3 PM” cannot simply become an API parameter. It must pass semantic analysis, task state, and planning. Parameters carry value, source, and status; tasks carry conversation, task, and step identity.'}</p>{flow(`User Request\n    ↓\nSemantic Analysis\n    intent = create\n    object = calendar_event\n    date = tomorrow\n    start = 15:00\n    duration = 60\n    ↓\nTask / Parameter State\n    ↓\nPlanner → Tool Contract`)}<div className="principle-grid"><div><strong>Intent</strong><span>{zh ? '查询、创建、修改还是删除？' : 'Query, create, update, or delete?'}</span></div><div><strong>State</strong><span>{zh ? '不是简单 key=value，而是带来源和状态的参数。' : 'Not plain key=value: parameters carry provenance and status.'}</span></div><div><strong>IDs</strong><span>conversation_id · task_id · step_id · operation_id · execution_id</span></div></div></Chapter>

    <Chapter number="03 · CONNECTING TO THE REAL WORLD" title={zh ? '从 Mock Tool 到真实 macOS Calendar' : 'From Mock Tool to a real macOS Calendar'}><p>{zh ? 'Mock Tool 只能证明 Agent 认为自己执行了操作，不能证明 Calendar 真的发生了变化。于是执行边界进入一个拥有 macOS 权限的原生 Host。' : 'A Mock Tool only proves that the agent believes it executed an operation. It cannot prove that Calendar changed. The execution boundary therefore moved into a native host with macOS permissions.'}</p>{flow(`AgentRuntime → Tool Request\n             → MacAgentHost.app\n             → EventKit\n             → macOS Calendar\n             → query_calendar / Verification`)}<p>{zh ? 'Python Runtime 与 macOS Calendar Permission Boundary 不是同一个边界，所以使用 MacAgentHost、EventKit 和 JSON-lines contract 连接两侧。' : 'The Python Runtime and the macOS Calendar permission boundary are different boundaries, so MacAgentHost, EventKit, and a JSON-lines contract connect them.'}</p><div className="qa-callout"><strong>{zh ? '一个真实的工程转折' : 'A real engineering turn'}</strong><p>{zh ? 'persistent NSApplication 生命周期与 subprocess.run timeout 曾经冲突，后来演进为 stdin request → stdout ToolResult → controlled termination。' : 'The persistent NSApplication lifecycle conflicted with subprocess.run timeouts. The boundary evolved into stdin request → stdout ToolResult → controlled termination.'}</p></div></Chapter>

    <Chapter number="04 · FROM MAC TO IPHONE & SIRI" title={zh ? '从 Mac localhost 到 Siri / iPhone' : 'From Mac localhost to Siri and iPhone'}><p>{zh ? 'Mac 上能运行只是开始。Personal Agent 需要从 Terminal 走向 iPhone、Shortcut 和 Siri。' : 'Running on a Mac was only the beginning. A Personal Agent needs to move from the Terminal to iPhone, Shortcuts, and Siri.'}</p>{flow(`localhost 127.0.0.1:8000\n        ↓\nLAN access\n        ↓\nDHCP address changed\n        ↓\nstable HTTPS endpoint\n        ↓\nCloudflare Named Tunnel → 127.0.0.1:8000`)}<p>{zh ? '这条链路带来了鉴权、Bearer Token、HTTPS、localhost-only Agent Server 和不暴露公网 8000 端口等安全边界。公网与真机连接仍需单独验收。' : 'This path introduced authentication, Bearer tokens, HTTPS, a localhost-only Agent Server, and no public port 8000. Public and real-device connectivity still require separate acceptance.'}</p></Chapter>

    <Chapter number="05 · MULTI-TURN AGENT" title={zh ? '从单轮命令到真正的多轮 Agent' : 'From one-shot commands to a multi-turn agent'}><p>{zh ? '用户说“明天开会”时，Agent 不能猜开始时间和时长。它应该进入 waiting_clarification，向用户提问，再用同一个 conversation 找回原来的 task。' : 'When the user says “Create a meeting tomorrow,” the agent must not guess. It enters waiting_clarification, asks a question, and uses the same conversation to find the original task.'}</p>{flow(`same conversation → find waiting task\n        ↓\nsame task_id → analyzing_clarification\n        ↓\nparameter merge → planning → tool → verification`)}<p>{zh ? 'Clarification Resume 已在代码中实现，但真实 iPhone/Siri 多轮回归仍在进行，因此标记为“实现中 / 真机验证中”。' : 'Clarification Resume is implemented in code, but real iPhone/Siri multi-turn regression is still in progress.'}</p></Chapter>

    <Chapter number="06 · ARCHITECTURE EVOLUTION: V1 → V2" title={zh ? '从 Protocol V1 到 V2：一次真实的 Architecture Reconciliation' : 'From Protocol V1 to V2: a real architecture reconciliation'}><div className="evolution-grid"><div><span>Protocol V1 · historical / frozen</span><pre>{`Client → Agent → Tool Request\n       → Client executes Tool\n       → Tool Result → Agent`}</pre></div><div><span>Protocol V2 · current / canonical</span><pre>{`Client → AgentRuntime\n       → Tool Execution Layer\n       → MacAgentHost → EventKit`}</pre></div></div><p>{zh ? '真实实现逐渐形成后，Specification ≠ Implementation，Architecture Drift 暴露出来。之后才有 Audit、Conflict Discovery、Reconciliation、ADR 和 Protocol V2。V1 没有被删除，而是作为历史版本保留。' : 'As the real implementation formed, Specification ≠ Implementation and architecture drift became visible. That led to audit, reconciliation, an ADR, and Protocol V2. V1 was not deleted; it remains as historical context.'}</p><div className="principle-grid"><div><strong>Boundary</strong><span>Client-side execution → Runtime → Tool Execution Layer → MacAgentHost</span></div><div><strong>IDs</strong><span>operation_id = logical write; retry uses a new execution_id</span></div><div><strong>Contract</strong><span>{zh ? 'Tool Request / Result 变成内部执行合同。' : 'Tool Request / Result become internal execution contracts.'}</span></div></div></Chapter>

    <Chapter number="07 · RELIABILITY & VERIFICATION" title={zh ? 'Agent 怎么证明自己真的完成了任务？' : 'How does the agent prove it completed the task?'}><p>{zh ? '核心原则是：Tool Success ≠ Task Success。只有真实状态经过 Verification，Agent 才能返回 Final.success。' : 'The core rule is: Tool Success ≠ Task Success. Only real-state Verification can justify Final.success.'}</p>{flow(`Tool Execution → Tool Result\n              ↓\n       query_calendar / verify_state\n              ↓\n compare event_id · title · start · end\n              ↓\nVerified → success | mismatch → failure | unknown → unknown`)}<p>{zh ? '这一章还要处理 operation_id、重复防护、Retry、Unknown、Pre-execution safety 和 EventKit 的真实状态。系统不宣称 exactly-once。' : 'This boundary also covers operation_id, duplicate prevention, retry, unknown state, pre-execution safety, and real EventKit state. The system does not claim exactly-once.'}</p></Chapter>

    <Chapter number="08 · AGENT QA & EVALUATION" title={zh ? '做完 Agent 以后，我到底怎么测它？' : 'How do I test the agent?'}><p>{zh ? 'Agent QA 不是最后跑一遍测试，而是贯穿 Agent 构建过程：确定性测试、Agent Evaluation、Observability、Integration、E2E 和 Regression。' : 'Agent QA is not a final test run. It runs through the build: deterministic testing, Agent Evaluation, Observability, Integration, E2E, and Regression.'}</p><div className="qa-callout"><strong>Agent QA</strong><ul><li>Deterministic Testing</li><li>Agent Evaluation</li><li>Observability</li><li>Integration / E2E</li><li>Regression</li></ul><Link className="project-text-link" href="/agent-evaluation/calendar-agent-qa/">{zh ? '阅读：Calendar Agent QA：工具与测试体系完整指南 →' : 'Read: Calendar Agent QA and test strategy →'}</Link></div></Chapter>

    <Chapter number="09 · WHAT BROKE ALONG THE WAY" title={zh ? '真实故障时间线' : 'What broke along the way'}><div className="defect-table"><div><strong>问题</strong><strong>暴露的问题</strong><strong>最终改进</strong></div>{(zh ? [['Event 时间偏移','Timezone Context','Explicit IANA Timezone'],['iPhone 无法访问','localhost boundary','HTTP / LAN'],['DHCP 后失联','IP dependency','Named Tunnel'],['Tool success 但结果不确定','Missing verification','VerificationService'],['英文请求中文回复','Language propagation','Language handling'],['Clarification 第二轮消失','Resume / observability','Traceability'],['V1 与实现不一致','Architecture Drift','Protocol V2']] : [['Event time shifted','Timezone context','Explicit IANA timezone'],['iPhone could not connect','Localhost boundary','HTTP / LAN'],['DHCP broke the Shortcut','IP dependency','Named Tunnel'],['Tool success was uncertain','Missing verification','VerificationService'],['English request got Chinese reply','Language propagation','Language handling'],['Clarification answer disappeared','Resume / observability','Traceability'],['V1 diverged from implementation','Architecture drift','Protocol V2']]).map(row => <div key={row[0]}>{row.map(cell => <span key={cell}>{cell}</span>)}</div>)}</div></Chapter>

    <Chapter number="NEXT · PERSONAL AGENT" title={zh ? 'Calendar 只是第一个 Capability' : 'Calendar is only the first capability'}><p>{zh ? '下一步是 Production LLM、Agent Eval Dataset、Automated Evaluation 和 Continuous Evaluation；更远的路线才是 Reminder、Mail、Files、Obsidian、Browser、Computer Use，最终走向 Personal Agent。' : 'Next come a production LLM, an evaluation dataset, automated evaluation, and continuous evaluation; later come Reminder, Mail, Files, Obsidian, Browser, and Computer Use on the path to a Personal Agent.'}</p><Link className="project-text-link" href="/agent-evaluation/calendar-agent-qa/">{zh ? '继续阅读 Agent QA →' : 'Continue to Agent QA →'}</Link></Chapter>
  </div>;
}
